### ISSUE TITLE
need -std=c99 parameter when compile bin

### ISSUE THREAD

**Issue by w675881684** [pigirons/cpufp#1]
[@l /tmp/cpufp]# gcc -pthread -O3 -c smtl.c
smtl.c: In function ‘smtl_begin_tasks’:
smtl.c:331:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < sh->num_threads; i++)
     ^
smtl.c:331:5: note: use option -std=c99 or -std=gnu99 to compile your code
[@l /tmp/cpufp]# 
[@l /tmp/cpufp]# gcc -pthread -O3 -c smtl.c -std=c99
[@l /tmp/cpufp]#

**Comment by pigirons** [comment]
already fixed
