### ISSUE TITLE
compile error on wsl2 of win10

### ISSUE THREAD

**Issue by leafinsky-li** [pigirons/cpufp#12]
compile error on wsl2:
 asm/cpufp_kernel_x86_avx_vnni.S:16: Error: unsupported instruction `vpdpbusd'

cat /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm flush_l1d arch_capabilities

**Comment by zzk0** [comment]
duplicate issue: https://github.com/pigirons/cpufp/issues/11

You can just remove the related lines and files.

**Comment by pigirons** [comment]
fixed
