### ISSUE TITLE
Error when executing "sh build.sh"

### ISSUE THREAD

**Issue by VeritasFutureKF** [pigirons/cpufp#16]
when executing "sh build.sh",cmd line reported is as folllowed:
``/usr/bin/ld: smtl.o: in function `smtl_thread_func(void*)':
smtl.cpp:(.text+0x78): undefined reference to `pthread_setaffinity_np'
/usr/bin/ld: smtl.o: in function `smtl_init(smtl_t**, std::vector<int, std::allocator<int> >&)':
smtl.cpp:(.text+0x3ff): undefined reference to `pthread_create'
/usr/bin/ld: smtl.o: in function `smtl_fini(smtl_t*)':
smtl.cpp:(.text+0x639): undefined reference to `pthread_join'
``
when I add -lpthread in build.sh ,errors were still reported.

**Comment by baosiling** [comment]
me too.

**Comment by pigirons** [comment]
I refactored the code. Now all the pthread settings are in build_[x64|arm64|...].sh.
