### ISSUE TITLE
华为自研aarch64架构TAISHANV200M无法测试

### ISSUE THREAD

**Issue by sqsu-pg** [pigirons/cpufp#19]
测试时报错是无法识别的指令集

**Comment by pigirons** [comment]
可以看看build_dir/cpuid是否生成，运行一下看看返回什么

**Comment by 787500229** [comment]
> 可以看看build_dir/cpuid是否生成，运行一下看看返回什么

同上问题，有生成build_dir/cpuid，运行./cpufp --thread_pool=[0-1]，报错Illegal instruction (core dumped)，请问有什么解决方法吗 测试了其他服务器是正常运行的

**Comment by pigirons** [comment]
> > 可以看看build_dir/cpuid是否生成，运行一下看看返回什么
> 
> 同上问题，有生成build_dir/cpuid，运行./cpufp --thread_pool=[0-1]，报错Illegal instruction (core dumped)，请问有什么解决方法吗 测试了其他服务器是正常运行的

可以跑一下build_dir/cpuid看看返回结果吗

**Comment by 787500229** [comment]
> > > 可以看看build_dir/cpuid是否生成，运行一下看看返回什么
> > 
> > 
> > 同上问题，有生成build_dir/cpuid，运行./cpufp --thread_pool=[0-1]，报错Illegal instruction (core dumped)，请问有什么解决方法吗 测试了其他服务器是正常运行的
> 
> 可以跑一下build_dir/cpuid看看返回结果吗
返回结果是以下：
_I8MM_
_BF16_
_ASIMD_DP_
_ASIMD_HP_
_ASIMD_

**Comment by pigirons** [comment]
> > > > 可以看看build_dir/cpuid是否生成，运行一下看看返回什么
> > > 
> > > 
> > > 同上问题，有生成build_dir/cpuid，运行./cpufp --thread_pool=[0-1]，报错Illegal instruction (core dumped)，请问有什么解决方法吗 测试了其他服务器是正常运行的
> > 
> > 
> > 可以跑一下build_dir/cpuid看看返回结果吗
> > 返回结果是以下：
> > _I8MM_
> > _BF16_
> > _ASIMD_DP_
> > _ASIMD_HP_
> > _ASIMD_

我怀疑是芯片并不支持_I8MM_和_BF16_，但是不知道为什么检测出来了，等后面有芯片了可以测试下，给华为报个bug。

**Comment by sqsu-pg** [comment]
好的，大佬，最近一直还没测，我再测一下

---- 回复的原邮件 ----
| 发件人 | Yang ***@***.***> |
| 发送日期 | 2024年05月17日 14:39 |
| 收件人 | pigirons/cpufp ***@***.***> |
| 抄送人 | sqsu-pg ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [pigirons/cpufp] 华为自研aarch64架构TAISHANV200M无法测试 (Issue #19) |

可以看看build_dir/cpuid是否生成，运行一下看看返回什么

同上问题，有生成build_dir/cpuid，运行./cpufp --thread_pool=[0-1]，报错Illegal instruction (core dumped)，请问有什么解决方法吗 测试了其他服务器是正常运行的

可以跑一下build_dir/cpuid看看返回结果吗
返回结果是以下：
I8MM
BF16
ASIMD_DP
ASIMD_HP
ASIMD

我怀疑是芯片并不支持_I8MM_和_BF16_，但是不知道为什么检测出来了，等后面有芯片了可以测试下，给华为报个bug。

**Comment by Concyclics** [comment]
在cpuid中去掉I8MM和BF16可以正常测试。鲲鹏920系列是armv8的指令，这两个应该在v9里，可能因为flag被华为屏蔽所以错误检测了。

**Comment by pigirons** [comment]
> 在cpuid中去掉I8MM和BF16可以正常测试。鲲鹏920系列是armv8的指令，这两个应该在v9里，可能因为flag被华为屏蔽所以错误检测了。

其实i8mm和bf16是armv8.6引入的，算是neon的扩展。SVE里面有单独的SVEI8MM和SVEBF16。

**Comment by Concyclics** [comment]
了解了，感谢您的回复。

**Comment by ydcool** [comment]
> 在cpuid中去掉I8MM和BF16可以正常测试。鲲鹏920系列是armv8的指令，这两个应该在v9里，可能因为flag被华为屏蔽所以错误检测了。

同 HiSilicon Kunpeng-920, 修改了下编译脚本可以了 👍
```diff
# build_arm64.sh
     for SIMD in `$BUILD_DIR/cpuid`;
     do
+     if [ $SIMD = '_I8MM_' ] || [ $SIMD = '_BF16_' ];then
+       echo "SKIP CPUID $SIMD"
+       continue
+     fi
     SIMD_MACRO="$SIMD_MACRO-D$SIMD "
     SIMD_OBJ="$SIMD_OBJ$BUILD_DIR/$SIMD.o "
     as ${AS_EXTRA_FLAGS} -c $ASM/$SIMD.S -o $BUILD_DIR/$SIMD.o
 done
```
