### ISSUE TITLE
link with -lrt for old glibc

### ISSUE THREAD

**Issue by dongxiao92** [pigirons/cpufp#2]
The librt library needs to be specified exlicitly for systems with old glibc. 
On my machine with gcc 4.8.5 and glibc 2.12, adding the `-lrt` flag at the end of the last command in gen.sh resolves the compilation error.

The compilation errors are listed below.

> [dongxiao@695189 cpufp]$ ./build.sh
> smtl.c: In function ‘smtl_begin_tasks’:
> smtl.c:331:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
>      for (int i = 0; i < sh->num_threads; i++)
>      ^
> smtl.c:331:5: note: use option -std=c99 or -std=gnu99 to compile your code
> cpufp_x86.o: In function `cpufp_x86_fma':
> cpufp_x86.c:(.text+0xb9): undefined reference to `clock_gettime'
> cpufp_x86.c:(.text+0xf7): undefined reference to `clock_gettime'
> cpufp_x86.c:(.text+0x194): undefined reference to `clock_gettime'
> cpufp_x86.c:(.text+0x1d4): undefined reference to `clock_gettime'
> cpufp_x86.c:(.text+0x25e): undefined reference to `clock_gettime'
> cpufp_x86.o:cpufp_x86.c:(.text+0x282): more undefined references to `clock_gettime' follow
> collect2: error: ld returned 1 exit status

**Comment by pigirons** [comment]
already fixed
