### ISSUE TITLE
Intel Sapphire Rapids架构CPU编译错误

### ISSUE THREAD

**Issue by doujianli** [pigirons/cpufp#20]
CPU: Intel 8458P

\# ./build_x64.sh
x64/cpufp.cpp: In function ‘void cpufp_register_isa()’:
x64/cpufp.cpp:291:31: error: ‘avx512f_fp16_fma_f16f16f16’ was not declared in this scope; did you mean ‘avx512_fp16_fma_f16f16f16’?
  291 |         0x20000000LL, 1024LL, avx512f_fp16_fma_f16f16f16);
         |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
         |                               avx512_fp16_fma_f16f16f16
/usr/bin/ld: cannot find build_dir/cpufp.o: No such file or directory
collect2: error: ld returned 1 exit status

**Comment by pigirons** [comment]
Yes, it's a bug. I have no SPR CPU to test. Thank you for notice this bug. I have fixed it.
