### ISSUE TITLE
I can not get the tops on K1,  where I can modify ?

### ISSUE THREAD

**Issue by ArthurLiu-jbl** [pigirons/cpufp#26]
1. K1 system info:
Linux k1 6.1.15 #1.0 SMP PREEMPT Thu May 30 13:16:13 UTC 2024 riscv64 riscv64 riscv64 GNU/Linux
make sure  disable DVFS
![图片](https://github.com/user-attachments/assets/9199ae05-da40-4437-98d6-a923af222aa7)

![图片](https://github.com/user-attachments/assets/d3924377-6bc3-4dad-9c3b-7bb59e21b9d8)

2. but I can not get the 533 GFLOPS of vfmacc.vf on 8 threads.
also I can not get the 66 GFLOPS of vfmacc.vf on single core.
I can only achieve 80% performance, where I should modify on K1 or cpufp code.
![图片](https://github.com/user-attachments/assets/83544185-4570-4b8d-a02e-d63601454fc2)

**Comment by craft-zhang** [comment]
Hello, the benchmark data in the repository was obtained from an EVB with a 2GHz CPU. Most commercially available products use a 1.6GHz CPU, so you can expect to achieve about 80% of the benchmark performance.

**Comment by ArthurLiu-jbl** [comment]
Hello Craft zhang, thanks for your answer. Did you overclock the CPU?

**Comment by craft-zhang** [comment]
Yes, I did overclock, but the configuration of the overclocked motherboard is different from the current sales version, and it is not recommended to try it.

**Comment by ArthurLiu-jbl** [comment]
> Yes, I did overclock, but the configuration of the overclocked motherboard is different from the current sales version, and it is not recommended to try it.
thank you very much.
