### ISSUE TITLE
cpufp_kernel_x86_avx512_vnni.s:16: Error: no such instruction: `vpdpbusd %zmm0,%zmm0,%zmm0'

### ISSUE THREAD

**Issue by hxs7709** [pigirons/cpufp#3]
@pigirons 
Why this error appears in my build? Should I upgrade as to a new version? My "Test steps and Environment" is also listed below.
    cpufp_kernel_x86_avx512_vnni.s:16: Error: no such instruction: `vpdpbusd %zmm0,%zmm0,%zmm0'

PS: I already update gcc to 9.2.0 in Centos 7.7.
Thanks for your help.

/******Test steps and Environment********/
[root@baseimage cpufp]# as -o cpufp_kernel_x86_avx512_vnni.o cpufp_kernel_x86_avx512_vnni.s
cpufp_kernel_x86_avx512_vnni.s: Assembler messages:
cpufp_kernel_x86_avx512_vnni.s:16: Error: no such instruction: `vpdpbusd %zmm0,%zmm0,%zmm0'
cpufp_kernel_x86_avx512_vnni.s:17: Error: no such instruction: `vpdpbusd %zmm1,%zmm1,%zmm1'
cpufp_kernel_x86_avx512_vnni.s:18: Error: no such instruction: `vpdpbusd %zmm2,%zmm2,%zmm2'
cpufp_kernel_x86_avx512_vnni.s:19: Error: no such instruction: `vpdpbusd %zmm3,%zmm3,%zmm3'
cpufp_kernel_x86_avx512_vnni.s:20: Error: no such instruction: `vpdpbusd %zmm4,%zmm4,%zmm4'
cpufp_kernel_x86_avx512_vnni.s:21: Error: no such instruction: `vpdpbusd %zmm5,%zmm5,%zmm5'
cpufp_kernel_x86_avx512_vnni.s:22: Error: no such instruction: `vpdpbusd %zmm6,%zmm6,%zmm6'
cpufp_kernel_x86_avx512_vnni.s:23: Error: no such instruction: `vpdpbusd %zmm7,%zmm7,%zmm7'
cpufp_kernel_x86_avx512_vnni.s:24: Error: no such instruction: `vpdpbusd %zmm8,%zmm8,%zmm8'
cpufp_kernel_x86_avx512_vnni.s:25: Error: no such instruction: `vpdpbusd %zmm9,%zmm9,%zmm9'
[root@baseimage cpufp]#
[root@baseimage cpufp]#
[root@baseimage cpufp]# as --version
GNU assembler version 2.27-41.base.el7_7.1
Copyright (C) 2016 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.
[root@baseimage cpufp]#
[root@baseimage cpufp]#
[root@baseimage cpufp]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:              7
CPU MHz:               3099.998
BogoMIPS:              6199.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni

**Comment by xx205** [comment]
I use clang 10.0.1 as the compiler and the vnni assembly codes are successfully compiled.

Just modify gen.sh as the following and run it.

```
clang -pthread -O3 -c smtl.c
clang -c -o cpufp_kernel_x86_avx512f.o cpufp_kernel_x86_avx512f.s
clang -c -o cpufp_kernel_x86_avx512_vnni.o cpufp_kernel_x86_avx512_vnni.s
clang -c -o cpufp_kernel_x86_fma.o cpufp_kernel_x86_fma.s
clang -c -o cpufp_kernel_x86_avx.o cpufp_kernel_x86_avx.s
clang -c -o cpufp_kernel_x86_sse.o cpufp_kernel_x86_sse.s
clang -pthread -D_AVX512F_ -D_AVX512_VNNI_ -D_FMA_ -D_AVX_ -D_SSE_ -c cpufp_x86.c
clang -pthread -lrt -o cpufp smtl.o cpufp_x86.o cpufp_kernel_x86_avx512f.o cpufp_kernel_x86_avx512_vnni.o cpufp_kernel_x86_fma.o cpufp_kernel_x86_avx.o cpufp_kernel_x86_sse.o
```
