### ISSUE TITLE
arm64 cpufp在手机中运行失败

### ISSUE THREAD

**Issue by TULINGQAZ** [pigirons/cpufp#34]
arm64 cpufp在手机中运行需要重新构建交叉编译环境重新编译吗？build_arm64.sh运行后得到的文件是x86_64架构的文件

**Comment by pigirons** [comment]
交叉编译可能暂时做不到，因为现在获取指令都是基于本机的指令集。我后面想想办法，把获取指令集和利用相关信息进行编译独立开。

**Comment by pigirons** [comment]
交叉编译可能暂时做不到，因为现在获取指令都是基于本机的指令集。我后面想想办法，把获取指令集和利用相关信息进行编译独立开。
