### ISSUE TITLE
Error when executing "sh build.sh"

### ISSUE THREAD

**Issue by jjiantong** [pigirons/cpufp#7]
I got the following errors when executing `sh build.sh`
```
cpufp_x86.c: In function ‘main’:
cpufp_x86.c:333:51: error: ‘i’ undeclared (first use in this function)
  if (strspn(argv[1], "0123456789") == strlen(argv[i]))
                                                   ^
cpufp_x86.c:333:51: note: each undeclared identifier is reported only once for each function it appears in
cpufp_x86.c:334:3: error: expected expression before ‘int’
   int num_threads = atoi(argv[1]);
   ^
cpufp_x86.c:335:28: error: ‘num_threads’ undeclared (first use in this function)
  printf("Thread(s): %d\n", num_threads);
                            ^
gcc: error: cpufp_x86.o: No such file or directory
```

**Comment by colorjam** [comment]
@jjiantong I ran into the same error. Solve it by commenting `if (strspn(argv[1], "0123456789") == strlen(argv[i]))`.

**Comment by LingsiDS** [comment]
There are some minor errors on line 333 of the file cpufp_x86.c, which you can simply fix as follows  
```cpp
int num_threads = 0;
if (strspn(argv[1], "0123456789") == strlen(argv[1])) 
	num_threads = atoi(argv[1]);
printf("Thread(s): %d\n", num_threads);
if (num_threads <= 0) 
{
	printf("Reset Threads\n");
	exit(1);	
}
```

**Comment by hxer7963** [comment]
> There are some minor errors on line 333 of the file cpufp_x86.c, which you can simply fix as follows
> 
> ```c++
> int num_threads = 0;
> if (strspn(argv[1], "0123456789") == strlen(argv[1])) 
> 	num_threads = atoi(argv[1]);
> printf("Thread(s): %d\n", num_threads);
> if (num_threads <= 0) 
> {
> 	printf("Reset Threads\n");
> 	exit(1);	
> }
> ```

just init `int num_thread = 1;` to set default value, no need to exit the progress.
